version: "3"

services:
  frontend:
    build: ./frontend
    container_name: react-ui
    restart: always
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mern-network
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules

  backend:
    build: ./backend
    container_name: node-api
    restart: always
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    depends_on:
      - database
    networks:
      - mern-network
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules

  database:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    # volumes:
    #   - ./mongobackup:/data/db // Not needed as we are seeding each time the container starts up but if data was to be modified it is useful.
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge